general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ["shell-exec yasb", "shell-exec tacky-borders"]

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands:
    ["shell-exec taskkill /IM yasb.exe /IM tacky-borders.exe /F"]

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: "cloak"

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: "5px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "5px"
    right: "5px"
    bottom: "5px"
    left: "5px"

window_effects:
  focused_window:
    border:
      enabled: false
      color: "#8dbcff"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: false
      opacity: "95%"
  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: false
      opacity: "0%"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true
      shown_on_top: false
    fullscreen:
      maximized: false
      shown_on_top: false

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  - commands: ["ignore"]
    match:
      - window_process: { equals: "zebar" }
      - window_process: { equals: "yasb" }
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }
      - window_title: { equals: "Command Palette" }
  - commands: ["set-floating"]
    match:

binding_modes:
  # ─────────────────────────────
  # Resize mode
  # ─────────────────────────────
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  # ─────────────────────────────
  # Move Workspace Mode
  # ─────────────────────────────
  - name: "move-workspace"
    keybindings:
      # Move focused window to adjacent monitor workspaces
      - commands: ["move-workspace --direction left"]
        bindings: ["h", "left"]
      - commands: ["move-workspace --direction right"]
        bindings: ["l", "right"]
      - commands: ["move-workspace --direction up"]
        bindings: ["k", "up"]
      - commands: ["move-workspace --direction down"]
        bindings: ["j", "down"]
      - commands: ["move --workspace 1"]
        bindings: ["1"]
      - commands: ["move --workspace 2"]
        bindings: ["2"]
      - commands: ["move --workspace 3"]
        bindings: ["3"]
      - commands: ["move --workspace 4"]
        bindings: ["4"]
      - commands: ["move --workspace 5"]
        bindings: ["5"]
      - commands: ["move --workspace 6"]
        bindings: ["6"]
      - commands: ["move --workspace 7"]
        bindings: ["7"]
      - commands: ["move --workspace 8"]
        bindings: ["8"]
      - commands: ["move --workspace 9"]
        bindings: ["9"]
      # Exit mode
      - commands: ["wm-disable-binding-mode --name move-workspace"]
        bindings: ["escape", "enter"]

keybindings:
  # Resize mode
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["ctrl+alt+shift+r"]
  - commands: ["wm-enable-binding-mode --name move-workspace"]
    bindings: ["ctrl+alt+shift+w"]

  # Focus windows
  - commands: ["focus --direction left"]
    bindings: ["ctrl+alt+shift+u", "ctrl+alt+shift+left"]
  - commands: ["focus --direction right"]
    bindings: ["ctrl+alt+shift+i", "ctrl+alt+shift+right"]
  - commands: ["focus --direction up"]
    bindings: ["ctrl+alt+shift+o", "ctrl+alt+shift+up"]
  - commands: ["focus --direction down"]
    bindings: ["ctrl+alt+shift+p", "ctrl+alt+shift+down"]

  # Move windows
  - commands: ["move --direction left"]
    bindings: ["ctrl+alt+shift+h"]
  - commands: ["move --direction right"]
    bindings: ["ctrl+alt+shift+l"]
  - commands: ["move --direction up"]
    bindings: ["ctrl+alt+shift+k"]
  - commands: ["move --direction down"]
    bindings: ["ctrl+alt+shift+j"]

  # Disables window management and all other keybindings until alt+shift+p
  # is pressed again.
  - commands: ["wm-toggle-pause"]
    bindings: ["ctrl+alt+shift+end"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["ctrl+alt+shift+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["ctrl+alt+shift+f"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["ctrl+alt+shift+space"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["ctrl+alt+shift+t"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["ctrl+alt+shift+f"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["ctrl+alt+shift+m"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["ctrl+alt+shift+q"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["ctrl+alt+shift+e"]

  # Refresh.
  - commands: ["wm-redraw", "wm-reload-config"]
    bindings: ["ctrl+alt+shift+z"]

  - commands: ["shell-exec wt"]
    bindings: ["ctrl+alt+shift+enter"]

  # Focus the next/previous active workspace defined in `workspaces` config.
  - commands: ["focus --next-active-workspace"]
    bindings: ["ctrl+alt+shift+s"]
  - commands: ["focus --prev-active-workspace"]
    bindings: ["ctrl+alt+shift+a"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["ctrl+alt+shift+d"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["ctrl+alt+shift+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["ctrl+alt+shift+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["ctrl+alt+shift+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["ctrl+alt+shift+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["ctrl+alt+shift+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["ctrl+alt+shift+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["ctrl+alt+shift+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["ctrl+alt+shift+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["ctrl+alt+shift+9"]
