[tools]
# Universal / Multi-platform tools
#7zip = { all = "7zip" }
#act = { all = "act" }

atuin = "atuin"
bat = "bat"
#biome = { all = "biome" }

bottom = "bottom"

#bruno = { all = "bruno" }
#cartero = { all = "cartero" }
#dart = { all = "dart" }
#difftastic = { all = "difftastic" }

discord = "discord"

#dotnet-sdk = { all = "dotnet-sdk" }

dust = "dust"

fastfetch = "fastfetch"

fd = "fd"

fzf = "fzf"

#git = { all = "git" }
#helix = { all = "helix" }
#jq = { all = "jq" }
#lazygit = { all = "lazygit" }
#obsidian = { all = "obsidian" }

opencode = "opencode"

podman = "podman"

ripgrep = "ripgrep"

#rustup = { all = "rustup" }
#scc = { all = "scc" }

starship = "starship"

#tailwindcss = { all = "tailwindcss" }
#taplo = { all = "taplo" }
#typst = { all = "typst" }

vivid = "vivid"

#volta = { scoop = "volta" }
#yazi = { all = "yazi" }
#zig = { all = "zig" }

zoxide = "zoxide"

# Mapped / Naming differences

[tools.gh]
pacman = "github-cli"
scoop = "gh"

#delta = { all = "delta", brew = "git-delta", pacman = "git-delta" }
#ov = { all = "ov", brew = "noborus/tap/ov" }

# Windows Specific (Scoop)
#gsudo = { scoop = "gsudo" }

sourcegit = "sourcegit"
dark = "dark"
everything = "everything"
glazewm = "glazewm"
innounp = "innounp"
postgrestools = "postgrestools"
scoop-search = "scoop-search"
tacky-borders = "tacky-borders"
yasb = "yasb"
zebar = "zebar"

# Arch btw

bitwarden = "bitwarden"
bitwarden-cli = "bitwarden-cli"
rofi = "rofi"
cascadia-code = "ttf-cascadia-code"
