[[packages.windows.scoop]]
bucket = "main"
id = "ov"
cmd = "ov"

[[packages.windows.scoop]]
bucket = "main"
id = "difftastic"
cmd = "difft"

[[packages.windows.scoop]]
bucket = "main"
id = "bottom"
cmd = "btm"

[[packages.windows.scoop]]
bucket = "main"
id = "scc"
cmd = "scc"

[[packages.windows.scoop]]
bucket = "main"
id = "jq"
cmd = "jq"

[[packages.windows.scoop]]
bucket = "main"
id = "delta"
cmd = "delta"

[[packages.windows.scoop]]
bucket = "main"
id = "dust"
cmd = "dust"

[[packages.windows.scoop]]
bucket = "main"
id = "fastfetch"
cmd = "fastfetch"

[[packages.windows.scoop]]
bucket = "main"
id = "fd"
cmd = "fd"

[[packages.windows.scoop]]
bucket = "main"
id = "fzf"
cmd = "fzf"

[[packages.windows.scoop]]
bucket = "main"
id = "gh"
cmd = "gh"

[[packages.windows.scoop]]
bucket = "main"
id = "gsudo"
cmd = "gsudo"

[[packages.windows.scoop]]
bucket = "main"
id = "rustup-msvc"
cmd = "rustup-msvc"

[[packages.windows.scoop]]
bucket = "main"
id = "helix"
cmd = "hx"

[[packages.windows.scoop]]
bucket = "extras"
id = "lazygit"
cmd = "lazygit"

[[packages.windows.scoop]]
bucket = "extras"
id = "sourcegit"
cmd = "sourcegit"

[[packages.windows.scoop]]
bucket = "main"
id = "podman"
cmd = "podman"

[[packages.windows.scoop]]
bucket = "main"
id = "typst"
cmd = "typst"

[[packages.windows.scoop]]
bucket = "main"
id = "act"
cmd = "act"

[[packages.windows.scoop]]
bucket = "main"
id = "starship"
cmd = "starship"

[[packages.windows.scoop]]
bucket = "main"
id = "ripgrep"
cmd = "rg"


[[packages.windows.scoop]]
bucket = "main"
id = "zoxide"
cmd = "zoxide"

[[packages.windows.scoop]]
bucket = "main"
id = "zig"
cmd = "zig"

[[packages.windows.scoop]]
bucket = "main"
id = "bat"
cmd = "bat"

[[packages.windows.winget]]
id = "sharkdp.vivid"
cmd = "vivid"

[[packages.windows.winget]]
id = "Microsoft.PowerToys"

[packages.linux]
brews = [
    "bottom",
    "git-delta",
    "dust",
    "fastfetch",
    "fd",
    "gh",
    "helix",
    "lazygit",
    "starship",
    "typst",
    "ripgrep",
    "vivid",
    "zoxide",
    "zig",
    "noborus/tap/ov",
]
apts = ["podman", "dotnet-sdk-9.0"]
casks = []

[packages.linux.cmds]
rustup = ["/bin/bash", "-c", "curl -fsSL https://sh.rustup.rs"]
[[packages.crossplatform.rust]]
cmd = "cargo install atuin"
pkgName = "atuin"
custom = 'gh run list --repo Mgniquick/atuin-win --status completed --limit 1 --json databaseId -q ".[].databaseId" | gh run download $in --repo Magniquick/atuin-win'
